name: Build CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Copy index.html to 404.index
      run: cp dist/index.html dist/404.html
      
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: ${{ secrets.EMAIL }}
        build_dir: dist
        branch: gh-pages
        cname: ntpu-graduate.littlechin.tw