name: Build CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install
      run: npm install
    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash
    - name: Build
      run: bun run build
    - name: Copy index.html to 404.index
      run: cp dist/index.html dist/404.html
      
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: ${{ secrets.EMAIL }}
        build_dir: dist
        branch: gh-pages